const trainData = [
  {
    id: 1,
    name: "Rajdhani Express",
    number: "12345",
    type: "Express",
    departure: "Mumbai",
    arrival: "Delhi",
    duration: "16h:30m",
    price: "₹2,500",
    availability: "Available",
    image: "https://img.freepik.com/free-vector/high-speed-realistic-modern-train-locomotive-railroad_1284-7135.jpg?",
  },
  {
    id: 2,
    name: "Shatabdi Express",
    number: "12001",
    type: "Superfast",
    departure: "Chennai",
    arrival: "Bangalore",
    duration: "5h:45m",
    price: "₹1,200",
    availability: "Limited",
    image: "https://img.freepik.com/premium-vector/isolated-train-white-background_951778-1040.jpg",
  },
  {
    id: 3,
    name: "Duronto Express",
    number: "12285",
    type: "Express",
    departure: "Kolkata",
    arrival: "Mumbai",
    duration: "18h:20m",
    price: "₹2,800",
    availability: "Available",
    image: "https://png.pngtree.com/background/20230527/original/pngtree-white-subway-train-on-white-background-picture-image_2753861.jpg",
  },
  {
    id: 4,
    name: "Garib Rath",
    number: "12909",
    type: "Superfast",
    departure: "Hyderabad",
    arrival: "Delhi",
    duration: "22h:10m",
    price: "₹1,500",
    availability: "Waitlisted",
    image: "https://img.pikbest.com/wp/202345/orange-and-white-background-an-black-train-cartoon-on_9600981.jpg!w700wp",
  },
  {
    id: 5,
    name: "Vande Bharat",
    number: "22439",
    type: "Superfast",
    departure: "Lucknow",
    arrival: "Delhi",
    duration: "6h:10m",
    price: "₹2,200",
    availability: "Available",
    image: "https://img.lovepik.com/bg/20240423/white-background-isolated-3d-rendering-of-a-freight-train_7230929_wh300.jpg",
  },
  {
    id: 6,
    name: "Tejas Express",
    number: "22120",
    type: "Express",
    departure: "Ahmedabad",
    arrival: "Mumbai",
    duration: "6h:55m",
    price: "₹2,500",
    availability: "Limited",
    image: "https://www.shutterstock.com/image-vector/illustration-train-engine-locomotive-260nw-2337336431.jpg",
  },
  {
    id: 7,
    name: "Humsafar Express",
    number: "12595",
    type: "Express",
    departure: "Patna",
    arrival: "Delhi",
    duration: "14h:40m",
    price: "₹2,000",
    availability: "Waitlisted",
    image: "https://www.shutterstock.com/image-photo/diesel-electric-locomotive-isolated-on-260nw-1110112223.jpg",
  },
  {
    id: 8,
    name: "Maharaja Express",
    number: "12439",
    type: "Luxury",
    departure: "Jaipur",
    arrival: "Mumbai",
    duration: "10h:30m",
    price: "₹5,500",
    availability: "Available",
    image: "https://png.pngtree.com/thumb_back/fh260/background/20230526/pngtree-3d-model-of-a-rapid-transport-train-image_2638453.jpg",
  },
];

export default trainData;