// src/config/trainData.js

const trainData = [
    {
      id: 1,
      name: "Rajdhani Express",
      number: "12301",
      departure: "10:00 AM - Mumbai",
      arrival: "6:30 PM - Delhi",
      duration: "8h 30m",
      price: "₹2200",
      availability: "Available",
    },
    {
      id: 2,
      name: "Shatabdi Express",
      number: "12002",
      departure: "6:00 AM - Delhi",
      arrival: "12:30 PM - Chandigarh",
      duration: "6h 30m",
      price: "₹1050",
      availability: "Limited",
    },
    {
      id: 3,
      name: "Duronto Express",
      number: "12245",
      departure: "8:15 PM - Kolkata",
      arrival: "10:00 AM - Mumbai",
      duration: "13h 45m",
      price: "₹2750",
      availability: "Available",
    },
    {
      id: 4,
      name: "Garib Rath",
      number: "12909",
      departure: "9:30 PM - Chennai",
      arrival: "8:00 AM - Bangalore",
      duration: "10h 30m",
      price: "₹850",
      availability: "Waitlist",
    },
    {
      id: 5,
      name: "Tejas Express",
      number: "22119",
      departure: "6:30 AM - Mumbai",
      arrival: "1:00 PM - Goa",
      duration: "6h 30m",
      price: "₹1350",
      availability: "Available",
    },
    {
      id: 6,
      name: "Vande Bharat Express",
      number: "22439",
      departure: "3:00 PM - Ahmedabad",
      arrival: "9:00 PM - Mumbai",
      duration: "6h 00m",
      price: "₹1600",
      availability: "Limited",
    },
    {
      id: 7,
      name: "Humsafar Express",
      number: "20911",
      departure: "5:00 PM - Jaipur",
      arrival: "8:30 AM - Lucknow",
      duration: "15h 30m",
      price: "₹1450",
      availability: "Available",
    },
    {
      id: 8,
      name: "Kolkata Mail",
      number: "12322",
      departure: "7:45 AM - Hyderabad",
      arrival: "6:15 PM - Kolkata",
      duration: "10h 30m",
      price: "₹1850",
      availability: "Available",
    },
  ];
  
  export default trainData;  